README.md
Some simple typos and a bit of formatting to make it look nicer :)
I know one of the snippets is actually JSON, but I used YAML syntax highlighting because the snippet is not valid JSON (due to the ellipses). YAML is a superset of JSON so everything's fine.
=> Fixed typos and formatting

README.md, config/node/resources/config-harvesting.properties.mustache, docs/config.md, docs/report.md, docs/start.md, presets/descriptions.yml, presets/shared.yml, src/commands/config.ts, src/commands/report.ts, src/commands/run.ts, src/model/ConfigPreset.ts, src/service/BootstrapService.ts, src/service/BootstrapUtils.ts, src/service/CertificateService.ts, src/service/ConfigService.ts, src/service/ReportService.ts, test/expected-api-node-config.csv, test/expected-api-node-config.rst, test/service/BootstrapUtils.test.ts, test/service/ReportService.test.ts
Hi @segfaultxavi @rg911 
I've added the "report" command that allows you to create RST files reporting the configured properties. Files are created in the `./target/report` folder
Examples:
```
symbol-bootstrap config --report 
symbol-bootstrap config --report -p testnet -a dual
symbol-bootstrap start --report
symbol-bootstrap report (after running a config)
```
An example of the generated report is the following:
https://github.com/nemtech/symbol-bootstrap/blob/config-report/test/expected-api-node-config.rst
The properties types and descriptions are kept in this [descriptions.yml](https://github.com/nemtech/symbol-bootstrap/blob/config-report/presets/descriptions.yml) file. The list is not comprehensive yet, we need to update the descriptions.yml file with all the possible keys. 
The …
=> Report command

src/model/Addresses.ts, src/service/CertificateService.ts, src/service/ConfigService.ts, test/certificates/output.txt, test/service/CertificateService.test.ts
Exposing node TLS certificates in addresses.yml so node admins can share it for delegate harvesting
Fixes https://github.com/nemtech/symbol-bootstrap/issues/65
=> Exposing node certificate on address.yml

CHANGELOG.md, README.md, docs/clean.md, docs/compose.md, docs/config.md, docs/healthCheck.md, docs/link.md, docs/report.md, docs/resetData.md, docs/run.md, docs/start.md, docs/stop.md, presets/testnet/assembly-api.yml, presets/testnet/assembly-dual.yml, src/model/DockerCompose.ts, src/service/BootstrapUtils.ts, src/service/CertificateService.ts, src/service/ConfigLoader.ts, src/service/ConfigService.ts, test/composes/expected-testnet-dual-compose.yml, test/service/BootstrapUtils.test.ts, test/service/ComposeService.test.ts, test/service/ConfigLoader.test.ts
Few fixes:
1 - mem_limit in testnet's mongo to 50% of the machine configuring bootstrap (creating the compose file)
2 - Fixed memory leak when concatenating logText on long span
3 - Masking 64 hex keys HIDDEN_KEY on logs (we may need to replicate this in other places)
4 - Only copying required configuration files and certificates to Rest from server to reduce the risk of exposing configuration if the rest box gets compromised
=> Security - Memory Limit DB

src/service/BootstrapUtils.ts, src/service/ComposeService.ts, test/composes/expected-docker-compose-bootstrap-custom-compose.yml, test/composes/expected-docker-compose-bootstrap-full.yml, test/composes/expected-docker-compose-bootstrap-repeat.yml, test/composes/expected-docker-compose-bootstrap.yml, test/composes/expected-testnet-voting-compose.yml, test/service/BootstrapUtils.test.ts, test/service/ComposeService.test.ts, test/voting_preset.yml
Small improvement allowing users to remove default values from presets. For example:
````
databases:
- compose:
mem_limit: ~
````
It also removes unnecessary empty fields from docker compose. 
Related to https://github.com/nemtech/symbol-bootstrap/issues/101 (Although it would need the memory limit most likely)
=> Pruning compose files

cmds/start-bootstrap-full.sh, docs/presetGuides.md, presets/shared.yml, src/model/ConfigPreset.ts, src/model/DockerCompose.ts, src/service/ComposeService.ts, test/composes/expected-docker-compose-bootstrap-custom.yml, test/custom_preset.yml, test/full_preset.yml, test/service/ComposeService.test.ts
**Enable compose debug mode**
It adds debug attributes to the docker compose services. The attributes are:
```
security_opt:
- 'seccomp:unconfined'
cap_add:
- ALL
privileged: true 
```
By default, debug mode is disabled. You can enable debug mode in each service.
````
gateways:
- dockerComposeDebugMode: true # debug mode in gateway
nodes:
- dockerComposeDebugMode: true # debug mode in node
brokerDockerComposeDebugMode: true # debug mode in broker
````
Alternatively, you can enable debug mode for all the services, but then disable them by one by. 
````
dockerComposeDebugMode: true # adds debug mode attributes to all the services
databases:
- dockerComposeDebugMode: false # excluding the database
nodes:
- brokerDockerComposeDebugMode: false # excluding the broker
````
(This is the …
=> Compose Debug Mode

CHANGELOG.md, config/node/agent/agent.properties.mustache
Added controller public key to the agent configuration. 
The controller account/public key is the recipient address for the supernode registration. This public key is not used yet but we may use it for agent->agent validation.
=> Controller public key agent configuration

README.md, cmds/start-bootstrap.sh, config/docker/server/startBroker.sh.mustache, config/docker/server/startServer.sh.mustache, docs/clean.md, docs/compose.md, docs/config.md, docs/enrolSupernode.md, docs/healthCheck.md, docs/link.md, docs/report.md, docs/resetData.md, docs/run.md, docs/start.md, docs/stop.md, src/service/ComposeService.ts, test/composes/expected-docker-compose-bootstrap-custom.yml, test/composes/expected-docker-compose-bootstrap-full.yml, test/composes/expected-docker-compose-bootstrap-repeat.yml, test/custom_bootstrap.yml, test/service/ComposeService.test.ts
I've added core dumps to the server docker scripts. 
When the user runs with a `dockerComposeDebugMode: true` custom preset flag, the nodes will set the core dumps to be saved in the node's ./logs target folder. The only caveat is that the node will run as root as the server docker image doesn't have the `sudo` command installed. Note, the user can bootstrap without sudo, just that the generated service will run as root (by excluding the user: from node services in the compose file). 
Fixes https://github.com/nemtech/symbol-bootstrap/issues/71
=> Core dump when dockerComposeDebugMode: true

CHANGELOG.md, src/service/BootstrapUtils.ts, src/service/ComposeService.ts
When running with root user.
I'm not a super fan of changing the permissions to 0x666 but the files are public files, the collection indexes js scripts. I think it's fine
Fixes https://github.com/nemtech/symbol-bootstrap/issues/197
It most likely fixes https://github.com/nemtech/symbol-bootstrap/issues/233 but I haven't tried the docker-compose over docker setup
=> Fixed `failed to load: /docker-entrypoint-initdb.d/mongoDbPrepare.js`

.prettierignore, presets/bootstrap/network.yml, presets/mainnet/network.yml, presets/shared.yml, presets/testnet/network.yml, test/composes/expected-docker-compose-bootstrap-custom-compose.yml, test/composes/expected-docker-compose-bootstrap-custom.yml, test/composes/expected-docker-compose-bootstrap-full.yml, test/composes/expected-docker-compose-bootstrap-repeat.yml, test/composes/expected-docker-compose-bootstrap.yml, test/composes/expected-mainnet-api-compose.yml, test/composes/expected-mainnet-dual-compose.yml, test/composes/expected-testnet-api-compose.yml, test/composes/expected-testnet-dual-compose.yml, test/composes/expected-testnet-supernode-compose.yml, test/composes/expected-testnet-voting-compose.yml, test/reports/bootstrap-voting/rest-gateway-0-rest.json
Upgraded rest to 2.3.6-alpha
cmc rest module disabled on private networks
Fixes https://github.com/nemtech/symbol-bootstrap/issues/253
=> Upgraded rest to 2.3.6-alpha

CHANGELOG.md, docs/config.md, docs/enrollRewardProgram.md, docs/link.md, docs/start.md, src/commands/config.ts, src/service/AnnounceService.ts, src/service/CommandUtils.ts, src/service/ConfigLoader.ts, src/service/ConfigService.ts, src/service/LinkService.ts, src/service/RewardProgramService.ts
Code improvement around merging preset objects.
The `link` and `enrollRewardProgram` commands allow `--customPreset` to avoid password prompt when main private key is not stored in the target/addresses.yml file
=> fix: --customPreset in `link` and `enrollRewardProgram` commands.

CHANGELOG.md, src/service/RunService.ts
<docker-compose down> stops and removes the containers thus the files produced in the container get lost on each stop command.
We changed it to <docker-compose stop> in order to preserve the last state of the container and have a faster start-up.
=> fix: bootstrap stop command is changed to run  <docker-compose stop> instead of <docker-compose down>

CHANGELOG.md, README.md, docs/clean.md, docs/compose.md, docs/config.md, docs/decrypt.md, docs/encrypt.md, docs/enrollRewardProgram.md, docs/healthCheck.md, docs/link.md, docs/report.md, docs/resetData.md, docs/run.md, docs/start.md, docs/stop.md, docs/updateVotingKeys.md, docs/verify.md, package-lock.json, src/commands/updateVotingKeys.ts, test/service/BootstrapUtils.test.ts
How to replicate:
The user has bootstrap 1.0.6 installed and running.  The user installs bootstrap 1.0.7 and runs `updateVotingKeys` without `--
upgrade` the node. The current target folder created with 1.0.6 doesn't have `votingKeyDesiredLifetime` as it's a new property from 1.0.7. 
This PR hotfixes the issue.
Question, should we name this release 1.0.7-hotfix or 1.0.8? 
Note that we have alphas with 1.0.8 already, a 1.0.8 released hotfix will have fewer features than the alphas. New alphas would be 1.0.9-alpha. It's not a big issue as you need to specify the alpha version or alpha tag to get an alpha. Regular installs will use released versions.
=> fix: `updateVotingKeys` NAN fix when upgrading bootstrap cli

CHANGELOG.md, package-lock.json, package.json, src/service/RemoteNodeService.ts, test/service/RemoteNodeService.test.ts
Fixes https://github.com/symbol/symbol-bootstrap/issues/314
The issue wasn't the proxy, the issue was how the generated `symbol-statistics-service-typescript-fetch-client` handled errors. I have improved that library so the exceptions are handled internally. 
The plan is to move the rest-client generator to a submodule of  https://github.com/symbol/statistics-service that automatically builds clients when updating openapi.
=> fix: Fixed `symbol-statistics-service-typescript-fetch-client` exception handling.

src/service/ConfigService.ts
The peers json files does not get generated correctly after the statistics service implementation.
The issues are
1. API nodes are been placed in peers-p2p.json
2. Nodes that are not API been put into the peers-api.json
For local network, peer-0 and peer-1 nodes were not able to discover each other.
For mainnet, this would most likely cause the peers-api.json to be empty due to the fact that most of the network is dual nodes(includes api).
=> Fix peers json not getting generated correctly.

src/service/BootstrapService.ts
It doesn't add any value. It can hide important config that should be explicit and as soon as a one field needs to be customized, everyhing else would need to be provided.
To be merged after 1.1.1 release
=> fix: removed unnecessary default params

src/commands/compose.ts, src/commands/config.ts, src/commands/healthCheck.ts, src/commands/link.ts, src/commands/modifyMultisig.ts, src/commands/pack.ts, src/commands/report.ts, src/commands/resetData.ts, src/commands/run.ts, src/commands/start.ts, src/commands/updateVotingKeys.ts, src/commands/verify.ts, src/commands/wizard.ts, src/service/BootstrapService.ts, src/service/BootstrapUtils.ts, src/service/CertificateService.ts, src/service/ComposeService.ts, src/service/ConfigLoader.ts, src/service/ConfigService.ts, src/service/NemgenService.ts, src/service/ReportService.ts, src/service/VerifyService.ts, test/commands/Wizard.test.ts, test/service/CertificateService.test.ts, test/service/ComposeService.test.ts, test/service/ConfigLoader.test.ts, test/service/ConfigService.test.ts, test/service/ReportService.test.ts, test/service/VerifyService.test.ts
It can be resolved without client code intervention, it works better when bootstrap is installed as a library for an app.
Another pr for better custom app integration
To be merged after 1.1.1 release
=> fix: Removed npm module root folder location param.

docs/config.md, docs/pack.md, docs/start.md, src/commands/config.ts
Fixed inverted options, assembly <-> preset
=> fix: inverted preset and assembly options

src/service/ConfigService.ts, src/service/VotingKeyFileProvider.ts, src/service/VotingService.ts, src/service/index.ts
This improvement allows devs to use another mechanism for voting key file creating. I would be using this in 2 ways:
1) I have a suite of tests to be pushed that does deep-dir comparison of different setups. The unit test needs a way to generate static files so we can do the assertions on all the files.  
The incoming test and unit test file provider:
https://github.com/symbol/symbol-bootstrap/blob/networkPresetFile/test/service/BootstrapService.test.ts
https://github.com/symbol/symbol-bootstrap/blob/networkPresetFile/test/service/BootstrapService.test.ts#L55
I need other PRs before pushing those unit tests.
2) Symbol services pre-create the voting files when generating the nemesis block on new networks, so they can then be used when creating each node. Those files are stored in the …
=> fix: voting key file provider

src/model/Addresses.ts, src/model/ConfigPreset.ts, src/service/ConfigLoader.ts, src/service/ConfigService.ts, test/service/ConfigService.test.ts
~1. Fixed config/start --preset and --assembly options (it was the other way around)~ Already merged in another pr
2. Removed unnecessary currency names from custom preset. It can be provided and resolved from the `nemesis.mosaics` field
3. Moved "opt-in" addresses/balances from `nemesis` to `nemesis.mosiac`. User (or symbol-network) can provide balances for multiple mosaics, although most of the time there is only one nemesis mosaic (like xym).
4. Allow a node to be excluded from nemesis (no balance or linked transactions). 
5. Allow users to provide node nemesis balance. If the balance is calculated, it will be less than  `maxHarvesterBalance` 
6. Better nemesis supply distribution and exception handling. Added unit tests.  
If this is too much I can split further. Note I would be …
=> Nemesis configuration improvements

package-lock.json
~~fix: updated sdk to latest 1.0.3~~
Audit fix, Updated oclif to latest since audit patch was failing. Generated docs is slightly different 
Replace '@oclif/test' with standard 'chai' imports
-mocha upgrade to 9.1.3
-eslint upgrade to 7.32.0
-create-ts-index to 1.13.7
No npm audit  vulnerabilities
=> fix: audit fix update

src/commands/verify.ts, src/service/VerifyService.ts, test/service/VerifyService.test.ts
It helps test the current bootstrap installation (for symbol-network)
It allows to reuse the reporting and verification errors.
Fixes https://github.com/symbol/symbol-bootstrap/issues/274
=> Verify service improvements.

alpha.sh
example:
bash alpha.sh my-experimental-tag
=> feat: allowing alpha.sh to publish custom npm tags

CHANGELOG.md, README.md, docs/renewCertificates.md, presets/shared.yml, presets/testnet/network.yml, src/commands/renewCertificates.ts, src/model/ConfigPreset.ts, src/service/CertificateService.ts, src/service/ConfigService.ts, src/service/RunService.ts, src/service/RuntimeService.ts, test/service/CertificateService.test.ts, test/service/RuntimeService.test.ts
feat: renewCertificates command - Only updates when the certificate expires in less than 30 days.
feat: certificate expiration warnings when upgrading - When the certificate expires in less than 30 days
feat: certificate expiration check in healthCheck  - Fails when the certificate expires in less than 30 days.
This is the initial work for the https://github.com/symbol/symbol-bootstrap/issues/285
Currently, this PR will help node admins renewing a node SSL certificate but without changing the node/transport private key (or main private key). Ideally, the SSL node certificate is renewed, a new node/transport private key should be used. This requires harvesters.dat migration and a node key relink (link command handles that already).
Once we have the harverters.dat migration tool (catapult …
=> SSL Certificate renew without node private key change

CHANGELOG.md, README.md, docs/renewCertificates.md, src/commands/renewCertificates.ts, src/service/CertificateService.ts, src/service/ConfigService.ts, test/service/CertificateService.test.ts
The `renewCertificates` command created on version 1.1.2 doesn't work when the certificates were created using an old version of bootstrap. 
To replicate the bug;
````shell
npm install -g symbol-bootstrap@1.1.0
symbol-bootstrap config -p mainnet -a dual --noPassword --reset
npm install -g symbol-bootstrap@1.1.2
echo 'certificateExpirationWarningInDays: 376' > custom-preset.yml  # Old way of forcing expiration
symbol-bootstrap renewCertificates --noPassword -c custom-preset.yml  # Raises an error!
````
This hotfix fixes that. Try.
````shell
npm install -g symbol-bootstrap@1.1.3-alpha-202201201146 # This branch alpha
echo 'certificateExpirationWarningInDays: 376' > custom-preset.yml  # Old way of forcing expiration
symbol-bootstrap renewCertificates --noPassword -c custom-preset.yml   # …
```
=> [hot-fix] renewCertificates on released 1.1.2

CHANGELOG.md, presets/shared.yml, test/composes/expected-docker-compose-bootstrap-custom-compose.yml, test/composes/expected-docker-compose-bootstrap-custom.yml, test/composes/expected-docker-compose-bootstrap-demo.yml, test/composes/expected-docker-compose-bootstrap-dual.yml, test/composes/expected-docker-compose-bootstrap-repeat.yml, test/composes/expected-docker-compose-bootstrap.yml, test/composes/expected-mainnet-api-compose.yml, test/composes/expected-mainnet-custom-services.yml, test/composes/expected-mainnet-dual-compose.yml, test/composes/expected-mainnet-peer-compose.yml, test/composes/expected-testnet-api-compose.yml, test/composes/expected-testnet-dual-compose.yml, test/composes/expected-testnet-httpsproxy-compose.yml, test/composes/expected-testnet-native-ssl-compose.yml, test/composes/expected-testnet-peer-compose.yml, test/composes/expected-testnet-voting-compose.yml
Fixes the openssl security vulnerability [issue](https://www.opencve.io/cve/CVE-2022-0778)
@fboucquez I think it's ready to be merged now but could you pls check with @Wayonb before you merge & release? Thanks :)
=> fix: openssl security vulnerability fixed with symbol-server:gcc-10-10.0.3.3
