config/node/resources/config-node.properties.mustache
presets/descriptions.yml
presets/shared.yml
test/reports/bootstrap-voting/api-node-0-config.csv
test/reports/bootstrap-voting/api-node-0-config.rst
test/reports/bootstrap-voting/peer-node-0-config.csv
test/reports/bootstrap-voting/peer-node-0-config.rst
test/reports/bootstrap-voting/peer-node-1-config.csv
test/reports/bootstrap-voting/peer-node-1-config.rst
test/reports/testnet-api/api-node-config.csv
test/reports/testnet-api/api-node-config.rst
test/reports/testnet-dual-voting/api-node-config.csv
test/reports/testnet-dual-voting/api-node-config.rst
test/reports/testnet-peer/peer-node-config.csv
test/reports/testnet-peer/peer-node-config.rst

Rocksdb config

---

src/service/ComposeService.ts
test/composes/expected-docker-compose-bootstrap-full.yml
test/composes/expected-docker-compose-bootstrap-repeat.yml
test/composes/expected-docker-compose-bootstrap.yml
test/composes/expected-testnet-dual-compose.yml

Making /symbol-commands folders read-only.
Fixes docker compose's volumes security concerns

Explicit read only and read write docker compose services.

---

presets/shared.yml
presets/testnet/assembly-api.yml
presets/testnet/assembly-dual.yml
src/model/ConfigPreset.ts
src/service/BootstrapUtils.ts
src/service/ComposeService.ts
test/composes/expected-docker-compose-bootstrap-custom-compose.yml
test/composes/expected-docker-compose-bootstrap-full.yml
test/composes/expected-docker-compose-bootstrap-repeat.yml
test/composes/expected-docker-compose-bootstrap.yml
test/composes/expected-testnet-dual-compose.yml
test/composes/expected-testnet-supernode-compose.yml
test/composes/expected-testnet-voting-compose.yml

Removed mem_limit default
Fixes https://github.com/nemtech/symbol-bootstrap/issues/109

Mongo's wiredTigerCacheSizeGB

---

cmds/start-bootstrap-alpha.sh
cmds/start-bootstrap-custom.sh
cmds/start-bootstrap-full.sh
cmds/start-bootstrap-optin.sh
cmds/start-bootstrap-repeat.sh
cmds/start-bootstrap-sudo.sh
cmds/start-bootstrap.sh
src/commands/compose.ts
src/commands/config.ts
src/commands/link.ts
src/commands/report.ts
src/commands/resetData.ts
src/commands/run.ts
src/service/BootstrapUtils.ts
src/service/ComposeService.ts
src/service/ConfigLoader.ts
src/service/ConfigService.ts
src/service/CryptoUtils.ts
src/service/LinkService.ts
src/service/ReportService.ts
src/service/RunService.ts
src/service/SupernodeService.ts
test/service/AgentCertificateService.test.ts
test/service/CertificateService.test.ts
test/service/ComposeService.test.ts
test/service/ConfigLoader.test.ts
test/service/CryptoUtils.test.ts
test/service/LinkService.test.ts

PrivateKey attributes in addresses.yml and preset.yml files would be encrypted when `--password` is provided.
For example:
```
symbol-bootstrap start -p bootstrap -r  -t target/bootstrap --password 1234
```
Every time there is an operation that requires loading one of these encrypted files, the user would need to provide the password to decrypt it. 
Note that --password is not required by default. We could eventually require it. 
I've not encrypted the whole file so it can be user friendly yet secure
The encrypted file will look like this:
````
version: 2
networkType: 152
nemesisGenerationHashSeed: 8DFDAFC8A2816EFAA51601BF445DB06808AA00DC2FDF48D141420FE6E92FFFF3
nodes:
-
name: peer-node-0
friendlyName: peer-node-0
roles: 'Peer,Voting'
main:
privateKey: >- …
```

Password protection - Encrypted addreses.yml and preset.yml files

---

README.md
cmds/link-testnet-supernode-external-node.sh
docs/clean.md
docs/compose.md
docs/config.md
docs/healthCheck.md
docs/link.md
docs/report.md
docs/resetData.md
docs/run.md
docs/start.md
docs/stop.md
docs/supernode.md
src/service/AnnounceService.ts
src/service/BootstrapUtils.ts
src/service/ConfigService.ts
src/service/LinkService.ts
src/service/SupernodeService.ts
test/service/BootstrapUtils.test.ts
test/service/LinkService.test.ts
test/service/script.ts

Removed the need of checking network height
Improved validation around multisig accounts.

Fixed unlink command on voting key

---

src/service/ConfigService.ts

Minor thing, really. Just found it while browsing the code.

Change local variable names, for clarity

---

package-lock.json
package.json

Add autocomplete plugin (`@oclif/plugin-autocomplete`).

[Enhancement Proposal] Add autocomplete Plugin.

---

config/rest-gateway/rest.json.mustache
presets/shared.yml

Added poolSize to rest.json.mustache.

---

CHANGELOG.md
src/model/ConfigPreset.ts
src/service/RewardProgramService.ts
test/service/RewardProgramService.test.ts

enrolProgram: cannot be a boolean anymore
Voting is not required to enrol a program
Fixes https://github.com/nemtech/symbol-bootstrap/issues/150
Fixes https://github.com/nemtech/symbol-bootstrap/issues/148

Enrol Reward Program fix.

---

CHANGELOG.md
config/agent/agent.properties.mustache
presets/shared.yml
src/model/ConfigPreset.ts
src/service/AgentCertificateService.ts
src/service/ComposeService.ts
src/service/ConfigService.ts
test/composes/expected-testnet-supernode-compose.yml

Moved Reward Program Agent to its own service/container in docker-compose.yml.
Fixes https://github.com/nemtech/symbol-bootstrap/issues/159

Agent container service

---

CHANGELOG.md
package-lock.json
package.json
src/service/BootstrapUtils.ts
src/service/ComposeService.ts
src/service/ConfigService.ts

Fixes https://github.com/nemtech/symbol-bootstrap/issues/163 
Fixes https://github.com/nemtech/symbol-bootstrap/security/dependabot/package-lock.json/marked/open

Copy seed fix

---

presets/shared.yml
src/model/ConfigPreset.ts
src/service/ComposeService.ts
test/composes/expected-testnet-supernode-compose.yml

The symbol-node-rewards will automatically deploy the agent image

symbol-node-rewards-agent image

---

CHANGELOG.md
presets/shared.yml
src/model/ConfigPreset.ts
src/service/ConfigService.ts

Random and limit p2p api list.

---

CHANGELOG.md
presets/bootstrap/network.yml
presets/shared.yml
src/model/ConfigPreset.ts
src/service/ConfigService.ts
test/reports/mainnet-dual-voting/node-config.csv
test/reports/mainnet-dual-voting/node-config.rst
test/reports/mainnet-dual/node-config.csv
test/reports/mainnet-dual/node-config.rst
test/reports/mainnet-peer/node-config.csv
test/reports/mainnet-peer/node-config.rst
test/reports/testnet-dual-voting/api-node-config.csv
test/reports/testnet-dual-voting/api-node-config.rst
test/reports/testnet-peer-voting/peer-node-config.csv
test/reports/testnet-peer-voting/peer-node-config.rst
test/service/BootstrapUtils.test.ts
test/service/ReportService.test.ts

testnet and mainnet
After v7
Fixes https://github.com/nemtech/symbol-bootstrap/issues/205

beneficiaryAddress set to use the node's main account

---

CHANGELOG.md
presets/mainnet/assembly-api.yml
presets/mainnet/assembly-dual.yml
presets/testnet/assembly-api.yml
presets/testnet/assembly-dual.yml
src/service/ConfigLoader.ts
test/composes/expected-testnet-dual-compose.yml
test/composes/expected-testnet-supernode-compose.yml
test/composes/expected-testnet-voting-compose.yml

Fixes https://github.com/nemtech/symbol-bootstrap/issues/211

Closed broker port by default in mainnet and testnet

---

CHANGELOG.md
presets/shared.yml
src/model/ConfigPreset.ts
test/reports/bootstrap-voting/api-node-0-config.csv
test/reports/bootstrap-voting/api-node-0-config.rst
test/reports/bootstrap-voting/peer-node-0-config.csv
test/reports/bootstrap-voting/peer-node-0-config.rst
test/reports/bootstrap-voting/peer-node-1-config.csv
test/reports/bootstrap-voting/peer-node-1-config.rst
test/reports/mainnet-dual-voting/node-config.csv
test/reports/mainnet-dual-voting/node-config.rst
test/reports/mainnet-dual/node-config.csv
test/reports/mainnet-dual/node-config.rst
test/reports/mainnet-peer/node-config.csv
test/reports/mainnet-peer/node-config.rst
test/reports/testnet-api/api-node-config.csv
test/reports/testnet-api/api-node-config.rst
test/reports/testnet-dual-voting/api-node-config.csv
test/reports/testnet-dual-voting/api-node-config.rst
test/reports/testnet-peer-non-harvesting-voting/peer-node-config.csv
test/reports/testnet-peer-non-harvesting-voting/peer-node-config.rst
test/reports/testnet-peer-voting/peer-node-config.csv
test/reports/testnet-peer-voting/peer-node-config.rst

Improved custom preset enum types.

Changed default TransactionSelectionStrategy to oldest

---

.travis.yml
CHANGELOG.md
README.md

@rg911 we may need to do the same in the different projects. The first one on the list is important, is the one doing the special operations like release, alphas, docs, etc

Nodejs travis upgrade

---

config/rest-gateway/rest.json.mustache
presets/shared.yml
src/service/BootstrapUtils.ts
test/reports/bootstrap-voting/rest-gateway-0-rest.json
test/reports/mainnet-dual-voting/rest-gateway-rest.json
test/reports/mainnet-dual/rest-gateway-rest.json
test/reports/testnet-api/rest-gateway-rest.json
test/reports/testnet-dual-voting/rest-gateway-rest.json
test/service/ReportService.test.ts

Added CMC extension config
Added unit test comparing expected and current rest.json files
Added json file validation and formatting

Added configurable rest extensions

---

docs/presetGuides.md
package-lock.json
package.json
presets/shared.yml
src/model/ConfigPreset.ts
src/service/AgentCertificateService.ts
src/service/CertificateService.ts
src/service/ConfigService.ts
src/service/NemgenService.ts
src/service/SshpkService.ts
src/service/VotingService.ts
test/composes/expected-docker-compose-bootstrap-custom-compose.yml
test/composes/expected-docker-compose-bootstrap-custom.yml
test/composes/expected-docker-compose-bootstrap-full.yml
test/composes/expected-docker-compose-bootstrap-repeat.yml
test/composes/expected-docker-compose-bootstrap.yml
test/composes/expected-mainnet-api-compose.yml
test/composes/expected-mainnet-dual-compose.yml
test/composes/expected-mainnet-peer-compose.yml
test/composes/expected-testnet-api-compose.yml
test/composes/expected-testnet-dual-compose.yml
test/composes/expected-testnet-peer-compose.yml
test/composes/expected-testnet-supernode-compose.yml
test/composes/expected-testnet-voting-compose.yml
test/service/AgentCertificateService.test.ts
test/service/CertificateService.test.ts

The server is only have one image that includes both server and tools artifacts.

remove server tool image.

---

presets/shared.yml
test/reports/bootstrap-voting/api-node-0-config.csv
test/reports/bootstrap-voting/api-node-0-config.rst
test/reports/bootstrap-voting/peer-node-0-config.csv
test/reports/bootstrap-voting/peer-node-0-config.rst
test/reports/bootstrap-voting/peer-node-1-config.csv
test/reports/bootstrap-voting/peer-node-1-config.rst
test/reports/mainnet-dual-voting/node-config.csv
test/reports/mainnet-dual-voting/node-config.rst
test/reports/mainnet-dual/node-config.csv
test/reports/mainnet-dual/node-config.rst
test/reports/mainnet-peer/node-config.csv
test/reports/mainnet-peer/node-config.rst
test/reports/testnet-api/node-config.csv
test/reports/testnet-api/node-config.rst
test/reports/testnet-dual-voting/node-config.csv
test/reports/testnet-dual-voting/node-config.rst
test/reports/testnet-peer-non-harvesting-voting/node-config.csv
test/reports/testnet-peer-non-harvesting-voting/node-config.rst
test/reports/testnet-peer-voting/node-config.csv
test/reports/testnet-peer-voting/node-config.rst

Update server release version in the node config.

Update server version

---

CHANGELOG.md
package-lock.json

fix: dependencies upgrade

---

package.json
src/commands/verify.ts

fix: version check at package.json

---

CHANGELOG.md
src/commands/updateVotingKeys.ts

hot fix: `updateVotingKeys` invalid check bug.

---

CHANGELOG.md
presets/shared.yml
test/composes/expected-docker-compose-bootstrap-custom-compose.yml
test/composes/expected-docker-compose-bootstrap-custom.yml
test/composes/expected-docker-compose-bootstrap-full.yml
test/composes/expected-docker-compose-bootstrap-repeat.yml
test/composes/expected-docker-compose-bootstrap.yml
test/composes/expected-mainnet-api-compose.yml
test/composes/expected-mainnet-dual-compose.yml
test/composes/expected-testnet-api-compose.yml
test/composes/expected-testnet-dual-compose.yml
test/composes/expected-testnet-httpsproxy-compose.yml
test/composes/expected-testnet-native-ssl-compose.yml
test/composes/expected-testnet-voting-compose.yml

fix: updated change log for 1.1.0 release
To be merged before release

fix: rest upgrade to 2.3.7

---

CHANGELOG.md
presets/shared.yml
test/composes/expected-docker-compose-bootstrap-custom-compose.yml
test/composes/expected-docker-compose-bootstrap-custom.yml
test/composes/expected-docker-compose-bootstrap-full.yml
test/composes/expected-docker-compose-bootstrap-repeat.yml
test/composes/expected-docker-compose-bootstrap.yml
test/composes/expected-mainnet-api-compose.yml
test/composes/expected-mainnet-dual-compose.yml
test/composes/expected-testnet-api-compose.yml
test/composes/expected-testnet-dual-compose.yml
test/composes/expected-testnet-httpsproxy-compose.yml
test/composes/expected-testnet-native-ssl-compose.yml
test/composes/expected-testnet-voting-compose.yml

fix: Rest `2.3.9` upgrade

---

package-lock.json
package.json

Just SDK update
Audit fix is failing atm, need to revisit
https://github.com/symbol/symbol-bootstrap/pull/330

fix: sdk 1.0.3 upgrade

---

package-lock.json
package.json
test/commands/Wizard.test.ts
test/service/BootstrapServce.e2e.ts
test/service/BootstrapServce.test.ts
test/service/BootstrapUtils.test.ts
test/service/CertificateService.test.ts
test/service/ComposeService.test.ts
test/service/ConfigLoader.test.ts
test/service/ConfigService.test.ts
test/service/CryptoUtils.test.ts
test/service/LinkService.test.ts
test/service/LinkTransactionGenericFactory.test.ts
test/service/ReportService.test.ts
test/service/VerifyService.test.ts
test/service/VotingUtils.test.ts

fix: replaced @oclif/test with chai import
Unit test-related upgrade

fix: mocha lib upgrade

---

CHANGELOG.md
README.md
presets/assemblies/assembly-demo.yml
presets/assemblies/assembly-multinode.yml
presets/shared.yml
src/model/ConfigPreset.ts
src/service/BootstrapUtils.ts
src/service/ComposeService.ts
src/service/ConfigLoader.ts
src/service/ConfigService.ts
test/composes/expected-docker-compose-bootstrap-demo.yml
test/composes/expected-docker-compose-bootstrap-repeat.yml
test/custom_preset-aws.yml
test/custom_preset.yml
test/repeat_preset.yml

It doesn't support custom networks well enough. Configuration is hardcoded.

Wallet removed from demo preset

---

.github/workflows/alpha.yml
.github/workflows/release.yml
README.md
docs/e2eTesting.md

fix: Moved e2e testing to its own file
fix: Small docs improvements
fix: Marked release as draft

Doc Updates

---

README.md
src/service/AsyncUtils.ts
src/service/BootstrapUtils.ts
src/service/ConfigService.ts
src/service/FileSystemService.ts
src/service/MigrationService.ts
src/service/RunService.ts
src/service/ZipUtils.ts
src/service/index.ts
test/service/AsyncUtils.test.ts

fix: Moved Migration interface to MigrationService
fix: Moved validate seed to FileSystemService

fix: split BootstrapUtils into AsyncUtils

---

presets/mainnet/network.yml
presets/testnet/network.yml
src/commands/compose.ts
src/commands/pack.ts
src/commands/report.ts
src/model/ConfigPreset.ts
src/service/ComposeService.ts
src/service/ReportService.ts
test/service/ReportService.test.ts

fix: provided external working dir on reports and compose service

fix: allow external version to reports for unit testing

---

CHANGELOG.md
README.md
docs/compose.md
docs/config.md
docs/pack.md
docs/presetGuides.md
docs/start.md
package-lock.json
presets/assemblies/assembly-services.yml
presets/mainnet/network.yml
src/commands/compose.ts
src/commands/config.ts
src/commands/pack.ts
src/commands/wizard.ts
src/model/ConfigPreset.ts
src/service/CommandUtils.ts
src/service/ComposeService.ts
src/service/ConfigLoader.ts
src/service/ConfigService.ts
src/service/RemoteNodeService.ts
test/composes/expected-docker-compose-mainnet-services.yml
test/service/BootstrapServce.test.ts
test/service/ComposeService.test.ts
test/service/ConfigLoader.test.ts
test/unit-test-profiles/services_custom_preset.yml

fix: assembly order for docs
fix: added offline flag to commands.

feat: added services assembly

---

config/docker/mongo/mongoDbPrepare.js

add 3 indexs
transaction.mosaics.id
statement.receipts.targetAddress
statement.receipts.senderAddress

Update mongoDbPrepare.js for improving the response time #304
